### ISSUE TITLE
"--test-type-ui" switch breaks dll/portability

### ISSUE THREAD

**Issue by A-7666** [czyt/vivaldi_plus#35]
When "--test-type-ui" switch is used, the DLL stops working, the portability is broken, and the installed extensions disappear.

Checked with DLL version 1.5.7.

**Comment by czyt** [comment]
the `--test-type` switch ：

+ Basically the 2014 version of --enable-automation. [codesearch(https://cs.chromium.org/search/?q=kTestType%5Cb&type=cs)
+ It avoids creating application stubs in ~/Applications on mac.
+ It makes exit codes slightly more correct
+ windows navigation jumplists arent updated https://crbug.com/389375
+ doesn't start some chrome StartPageService
+ disables initializing chromecast service
+ "Component extensions with background pages are not enabled during tests because they generate a lot of background behavior that can interfere."
+ when quitting the browser, it disables additional checks that may stop that quitting process. (like unsaved form modifications or unhandled profile notifications..)

i am not much familiar with cpp,so I could debug to know which reason caused this.sorry about this.
